# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''  # 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''  # 'UA-112060364-1'

menu:
- {name: 'About', path: 'about', url: ''}
- {name: 'Contact', path: 'contact', url: ''}

dropdown_menu:
- {name: '자바스크립트', path: 'javascript', icon: 'javascript', url: ''}
- {name: '파이썬', path: 'python', icon: 'python', url: ''}
- {name: '장고, 플라스크', path: 'django', icon: 'django', url: ''}
- {name: '데이터베이스', path: 'database', icon: 'database', url: ''}
- {name: '도커', path: 'docker', icon: 'docker', url: ''}
- {name: '알고리즘, 코테', path: 'algorithm', icon: 'algorithm', url: ''}
- {name: 'CS', path: 'computer-science', icon: 'cs', url: ''}
- {name: 'WEB, HTTP', path: 'web', icon: 'web', url: ''}
- {name: '문제해결경험', path: 'solving-problem', icon: 'solving_problem', url: ''}
- {name: '잡동사니', path: 'etc', icon: 'package', url: ''}
- {name: '나무야 나무야', path: 'daily', icon: 'favicon', url: ''}
- {name: '데미안에게', path: 'demian', icon: 'book', url: ''}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/daesungra'}
# - {icon: 'twitter', link: 'https://twitter.com/daesungra'}
# - {icon: 'linkedin', link: 'http://www.linkedin.com/in/daesungra/'}
- {icon: 'envelope', link: 'daesungra@gmail.com'}
- {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
